export const aboutSchema = [
  {
    '@context': 'http://schema.org/',
    '@type': 'CreativeWork',
    text: 'Video creation company producing tailor-made corporate videos, explainer videos, promotional videos & employer branding videos for global enterprises',
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video Professionals',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/about',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video Professionals',
    alternateName: 'Video Professionals',
    url: 'https://www.redbangle.global/about',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/about',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video Professionals',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video Professionals',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Seamless Support',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/about',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Seamless Support',
    alternateName: 'Seamless Support',
    url: 'https://www.redbangle.global/about',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/about',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Seamless Support',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Seamless Support',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Who We Are',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/about',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Who We Are',
    alternateName: 'Who We Are',
    url: 'https://www.redbangle.global/about',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/about',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Who We Are',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Who We Are',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'What Do We Do ',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/about',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'What Do We Do ',
    alternateName: 'What Do We Do ',
    url: 'https://www.redbangle.global/about',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/about',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'What Do We Do ',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'What Do We Do ',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'What Makes Us Unique',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/about',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'What Makes Us Unique',
    alternateName: 'What Makes Us Unique ',
    url: 'https://www.redbangle.global/about',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/about',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'What Makes Us Unique',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'What Makes Us Unique',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Meet Our Team',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/about',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Meet Our Team',
    alternateName: 'Meet Our Team ',
    url: 'https://www.redbangle.global/about',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/about',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Meet Our Team',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Meet Our Team',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Meet Our Professionals',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/about',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Meet Our Professionals',
    alternateName: 'Meet Our Professionals ',
    url: 'https://www.redbangle.global/about',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/about',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Meet Our Professionals',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Meet Our Professionals',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Meet Our Crew',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/about',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Meet Our Crew',
    alternateName: 'Meet Our Crew ',
    url: 'https://www.redbangle.global/about',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/about',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Meet Our Crew',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Meet Our Crew',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Meet Our Leadership Team',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/about',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Meet Our Leadership Team',
    alternateName: 'Meet Our Leadership Team ',
    url: 'https://www.redbangle.global/about',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/about',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Meet Our Leadership Team',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Meet Our Leadership Team',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Global Team',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/about',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Global Team',
    alternateName: 'Global Team ',
    url: 'https://www.redbangle.global/about',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/about',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Global Team',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Global Team',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'International Professionals',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/about',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'International Professionals',
    alternateName: 'International Professionals ',
    url: 'https://www.redbangle.global/about',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/about',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'International Professionals',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'International Professionals',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video Creation Company',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/about',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video Creation Company',
    alternateName: 'Video Creation Company ',
    url: 'https://www.redbangle.global/about',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/about',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video Creation Company',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video Creation Company',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Team Culture',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/about',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Team Culture',
    alternateName: 'Team Culture',
    url: 'https://www.redbangle.global/about',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/about',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Team Culture',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Team Culture',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Professional Video Services',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/about',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Professional Video Services',
    alternateName: 'Professional Video Services',
    url: 'https://www.redbangle.global/about',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/about',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Professional Video Services',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Professional Video Services',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org/',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Video Professionals',
        item: 'https://www.redbangle.global/about',
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Seamless Support',
        item: 'https://www.redbangle.global/about',
      },
      {
        '@type': 'ListItem',
        position: 3,
        name: 'Who We Are',
        item: 'https://www.redbangle.global/about',
      },
      {
        '@type': 'ListItem',
        position: 4,
        name: 'What Do We Do',
        item: 'https://www.redbangle.global/about',
      },
      {
        '@type': 'ListItem',
        position: 5,
        name: 'What Makes Us Unique',
        item: 'https://www.redbangle.global/about',
      },
      {
        '@type': 'ListItem',
        position: 6,
        name: 'Meet Our Team',
        item: 'https://www.redbangle.global/about',
      },
      {
        '@type': 'ListItem',
        position: 7,
        name: 'Meet Our Professionals',
        item: 'https://www.redbangle.global/about',
      },
      {
        '@type': 'ListItem',
        position: 8,
        name: 'Meet Our Crew',
        item: 'https://www.redbangle.global/about',
      },
      {
        '@type': 'ListItem',
        position: 9,
        name: 'Meet Our Leadership Team',
        item: 'https://www.redbangle.global/about',
      },
      {
        '@type': 'ListItem',
        position: 10,
        name: 'Global Team',
        item: 'https://www.redbangle.global/about',
      },
      {
        '@type': 'ListItem',
        position: 11,
        name: 'International Professionals',
        item: 'https://www.redbangle.global/about',
      },
      {
        '@type': 'ListItem',
        position: 12,
        name: 'Team Culture',
        item: 'https://www.redbangle.global/about',
      },
      {
        '@type': 'ListItem',
        position: 13,
        name: 'Video Creation Company',
        item: 'https://www.redbangle.global/about',
      },
      {
        '@type': 'ListItem',
        position: 14,
        name: 'Professional Video Services',
        item: 'https://www.redbangle.global/about',
      },
    ],
  },
]
