export const campaignSchema = [
  {
    '@context': 'http://schema.org/',
    '@type': 'CreativeWork',
    text: 'Video creation company producing tailor-made corporate videos, explainer videos, promotional videos & employer branding videos for global enterprises',
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Best Commercial Campaigns',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Best Commercial Campaigns',
    alternateName: 'Best Commercial Campaigns',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Best Commercial Campaigns',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Best Commercial Campaigns',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Best Campaign Marketing',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Best Campaign Marketing',
    alternateName: 'Best Campaign Marketing',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Best Campaign Marketing',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Best Campaign Marketing',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Famous Advertising Campaigns',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Famous Advertising Campaigns',
    alternateName: 'Famous Advertising Campaigns',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Famous Advertising Campaigns',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Famous Advertising Campaigns',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Best Recruitment Campaigns',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Best Recruitment Campaigns',
    alternateName: 'Best Recruitment Campaigns',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Best Recruitment Campaigns',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Best Recruitment Campaigns',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Company Ad Campaigns',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Company Ad Campaigns',
    alternateName: 'Company Ad Campaigns',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Company Ad Campaigns',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Company Ad Campaigns',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video Ad Campaigns',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video Ad Campaigns',
    alternateName: 'Video Ad Campaigns',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video Ad Campaigns',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video Ad Campaigns',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Active Campaign',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Active Campaign',
    alternateName: 'Active Campaign',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Active Campaign',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Active Campaign',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Product Ads',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Product Ads',
    alternateName: 'Product Ads',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Product Ads',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Product Ads',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Corporate Ads',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Corporate Ads',
    alternateName: 'Corporate Ads',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Corporate Ads',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Corporate Ads',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Best Way To Advertise Your Business',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Best Way To Advertise Your Business',
    alternateName: 'Best Way To Advertise Your Business',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Best Way To Advertise Your Business',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Best Way To Advertise Your Business',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Brand Advertising',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Brand Advertising',
    alternateName: 'Brand Advertising',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Brand Advertising',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Brand Advertising',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Creative Campaigns',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Creative Campaigns',
    alternateName: 'Creative Campaigns',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Creative Campaigns',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Creative Campaigns',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Creative Ad',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Creative Ad',
    alternateName: 'Creative Ad',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Creative Ad',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Creative Ad',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Ad Campaigns',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Ad Campaigns',
    alternateName: 'Ad Campaigns',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Ad Campaigns',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Ad Campaigns',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Brand Campaigns',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Brand Campaigns',
    alternateName: 'Brand Campaigns',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Brand Campaigns',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Brand Campaigns',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Best Commercial Campaigns',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Best Commercial Campaigns',
    alternateName: 'Best Commercial Campaigns',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Best Commercial Campaigns',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Best Commercial Campaigns',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Great Ad Campaigns',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Great Ad Campaigns',
    alternateName: 'Great Ad Campaigns',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Great Ad Campaigns',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Great Ad Campaigns',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Creative Brand Campaigns',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Creative Brand Campaigns',
    alternateName: 'Creative Brand Campaigns',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Creative Brand Campaigns',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Creative Brand Campaigns',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Creative Marketing Campaigns',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/campaigns',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Creative Marketing Campaigns',
    alternateName: 'Creative Marketing Campaigns',
    url: 'https://www.redbangle.global/campaigns',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/campaigns',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Creative Marketing Campaigns',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Creative Marketing Campaigns',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org/',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Best Commercial Campaigns',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Best Campaign Marketing',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 3,
        name: 'Famous Advertising Campaigns',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 4,
        name: 'Best Recruitment Campaigns',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 5,
        name: 'Company Ad Campaigns',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 6,
        name: 'Video Ad Campaigns',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 7,
        name: 'Active Campaign',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 8,
        name: 'Product Ads',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 9,
        name: 'Corporate Ads',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 10,
        name: 'Best Way To Advertise Your Business',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 11,
        name: 'Brand Advertising',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 12,
        name: 'Creative Campaigns',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 13,
        name: 'Creative Ad',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 14,
        name: 'Ad Campaigns',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 15,
        name: 'Brand Campaigns',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 16,
        name: 'Best Commercial Campaigns',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 17,
        name: 'Great Ad Campaigns',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 18,
        name: 'Creative Brand Campaigns',
        item: 'https://www.redbangle.global/campaigns',
      },
      {
        '@type': 'ListItem',
        position: 19,
        name: 'Creative Marketing Campaigns',
        item: 'https://www.redbangle.global/campaigns',
      },
    ],
  },
]
