export const crewsSchema = [
  {
    '@context': 'http://schema.org/',
    '@type': 'CreativeWork',
    text: 'Video creation company producing tailor-made corporate videos, explainer videos, promotional videos & employer branding videos for global enterprises',
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Commercial Photographer',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Commercial Photographer',
    alternateName: 'Commercial Photographer',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Commercial Photographer',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Commercial Photographer',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Event Photographer',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Event Photographer',
    alternateName: 'Event Photographer',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Event Photographer',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Event Photographer',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Professional Photographers',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Professional Photographers',
    alternateName: 'Professional Photographers',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Professional Photographers',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Professional Photographers',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Photographers',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Photographers',
    alternateName: 'Photographers',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Photographers',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Photographers',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Photography Director',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Photography Director',
    alternateName: 'Photography Director',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Photography Director',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Photography Director',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video Director',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video Director',
    alternateName: 'Video Director',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video Director',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video Director',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Action Camera',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Action Camera',
    alternateName: 'Action Camera',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Action Camera',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Action Camera',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Drone With Camera',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Drone With Camera',
    alternateName: 'Drone With Camera',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Drone With Camera',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Drone With Camera',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Photography Crew',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Photography Crew',
    alternateName: 'Photography Crew',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Photography Crew',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Photography Crew',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video Crew',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video Crew',
    alternateName: 'Video Crew',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video Crew',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video Crew',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Company Headshots',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Company Headshots',
    alternateName: 'Company Headshots',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Company Headshots',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Company Headshots',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Hire Drone Videographer',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Hire Drone Videographer',
    alternateName: 'Hire Drone Videographer',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Hire Drone Videographer',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Hire Drone Videographer',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Event Photographer',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Event Photographer',
    alternateName: 'Event Photographer',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Event Photographer',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Event Photographer',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Commercial Photographer',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Commercial Photographer',
    alternateName: 'Commercial Photographer',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Commercial Photographer',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Commercial Photographer',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Corporate Professional Headshots',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Corporate Professional Headshots',
    alternateName: 'Corporate Professional Headshots',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Corporate Professional Headshots',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Corporate Professional Headshots',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Professional Photo Shoot',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Professional Photo Shoot',
    alternateName: 'Professional Photo Shoot',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Professional Photo Shoot',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Professional Photo Shoot',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video Film Company',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video Film Company',
    alternateName: 'Video Film Company',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video Film Company',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video Film Company',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Videographer For Rent ',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Videographer For Rent ',
    alternateName: 'Videographer For Rent ',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Videographer For Rent ',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Videographer For Rent ',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video Shoot',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video Shoot',
    alternateName: 'Video Shoot',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video Shoot',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video Shoot',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Cinematographer',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Cinematographer',
    alternateName: 'Cinematographer',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Cinematographer',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Cinematographer',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Videography',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Videography',
    alternateName: 'Videography',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Videography',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Videography',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Real Estate Photography',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Real Estate Photography',
    alternateName: 'Real Estate Photography',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Real Estate Photography',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Real Estate Photography',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Product Photography',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Product Photography',
    alternateName: 'Product Photography',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Product Photography',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Product Photography',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Aerial Photography',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Aerial Photography',
    alternateName: 'Aerial Photography',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Aerial Photography',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Aerial Photography',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Professional Photographer',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Professional Photographer',
    alternateName: 'Professional Photographer',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Professional Photographer',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Professional Photographer',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Headshot Photography',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Headshot Photography',
    alternateName: 'Headshot Photography',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Headshot Photography',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Headshot Photography',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Drone Photography',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Drone Photography',
    alternateName: 'Drone Photography',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Drone Photography',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Drone Photography',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Business Headshots',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Business Headshots',
    alternateName: 'Business Headshots',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Business Headshots',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Business Headshots',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Local Photographers',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Local Photographers',
    alternateName: 'Local Photographers',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Local Photographers',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Local Photographers',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Best Drone Photography',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Best Drone Photography',
    alternateName: 'Best Drone Photography',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Best Drone Photography',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Best Drone Photography',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Corporate Videographer',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Corporate Videographer',
    alternateName: 'Corporate Videographer',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Corporate Videographer',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Corporate Videographer',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Hire A Photographer',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Hire A Photographer',
    alternateName: 'Hire A Photographer',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Hire A Photographer',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Hire A Photographer',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Jewelry Photography',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Jewelry Photography',
    alternateName: 'Jewelry Photography',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Jewelry Photography',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Jewelry Photography',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Best Photographer For Wedding',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Best Photographer For Wedding',
    alternateName: 'Best Photographer For Wedding',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Best Photographer For Wedding',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Best Photographer For Wedding',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Camera Crew',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Camera Crew',
    alternateName: 'Camera Crew',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Camera Crew',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Camera Crew',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Digital Filmmaking',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Digital Filmmaking',
    alternateName: 'Digital Filmmaking',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Digital Filmmaking',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Digital Filmmaking',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Drone Photo',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Drone Photo',
    alternateName: 'Drone Photo',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Drone Photo',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Drone Photo',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Commercial Headshot',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Commercial Headshot',
    alternateName: 'Commercial Headshot',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Commercial Headshot',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Commercial Headshot',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Contemporary Corporate Headshots',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/crews',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Contemporary Corporate Headshots',
    alternateName: 'Contemporary Corporate Headshots',
    url: 'https://www.redbangle.global/crews',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/crews',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Contemporary Corporate Headshots',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Contemporary Corporate Headshots',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org/',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Commercial Photographer',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Event Photographer',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 3,
        name: 'Professional Photographers',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 4,
        name: 'Photographers',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 5,
        name: 'Photography Director',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 6,
        name: 'Video Director',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 7,
        name: 'Action Camera',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 8,
        name: 'Drone With Camera',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 9,
        name: 'Photography Crew',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 10,
        name: 'Video Crew',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 11,
        name: 'Company Headshots',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 12,
        name: 'Hire Drone Videographer',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 13,
        name: 'Event Photographer',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 14,
        name: 'Commercial Photographer',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 15,
        name: 'Corporate Professional Headshots',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 16,
        name: 'Corporate Videography',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 17,
        name: 'Professional Photo Shoot',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 18,
        name: 'Video Film Company',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 19,
        name: 'Videographer For Rent',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 20,
        name: 'Video Shoot',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 21,
        name: 'Cinematographer',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 22,
        name: 'Videography',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 23,
        name: 'Real Estate Photography',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 24,
        name: 'Product Photography',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 25,
        name: 'Aerial Photography',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 26,
        name: 'Professional Photographer',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 27,
        name: 'Headshot Photography',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 28,
        name: 'Drone Photography',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 29,
        name: 'Business Headshots',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 30,
        name: 'Local Photographers',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 31,
        name: 'Best Drone Photography',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 32,
        name: 'Corporate Videographer',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 33,
        name: 'Hire A Photographer',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 34,
        name: 'Jewelry Photography',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 35,
        name: 'Best Photographer For Wedding',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 36,
        name: 'Camera Crew',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 37,
        name: 'Digital Filmmaking',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 38,
        name: 'Drone Photo',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 39,
        name: 'Commercial Headshot',
        item: 'https://www.redbangle.global/crews',
      },
      {
        '@type': 'ListItem',
        position: 40,
        name: 'Contemporary Corporate Headshots',
        item: 'https://www.redbangle.global/crews',
      },
    ],
  },
]
