export const schemaHome = [
  {
    '@context': 'http://schema.org/',
    '@type': 'CreativeWork',
    text: 'Video creation company producing tailor-made corporate videos, explainer videos, promotional videos & employer branding videos for global enterprises',
  },
  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Corporate Video',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Corporate Video',
    alternateName: 'Corporate Video',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Corporate Video',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Corporate Video',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video Creation Company',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video Creation Company',
    alternateName: 'Video Creation Company',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video Creation Company',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video Creation Company',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Corporate Video Production Agency',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Corporate Video Production Agency',
    alternateName: 'Corporate Video Production Agency',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Corporate Video Production Agency',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Corporate Video Production Agency',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video Animation Services',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video Animation Services',
    alternateName: 'Video Animation Services',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video Animation Services',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video Animation Services',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Brand Video Agency',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Brand Video Agency',
    alternateName: 'Brand Video Agency',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Brand Video Agency',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Brand Video Agency',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Explainer Video Production',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Explainer Video Production',
    alternateName: 'Explainer Video Production',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Explainer Video Production',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Explainer Video Production',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Corporate Videographer',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Corporate Videographer',
    alternateName: 'Corporate Videographer',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Corporate Videographer',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Corporate Videographer',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video And Marketing',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video And Marketing',
    alternateName: 'Video And Marketing',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video And Marketing',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video And Marketing',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Photographers',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Photographers',
    alternateName: 'Photographers',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Photographers',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Photographers',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Drone Photography',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Drone Photography',
    alternateName: 'Drone Photography',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Drone Photography',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Drone Photography',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video Filming',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video Filming',
    alternateName: 'Video Filming',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video Filming',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video Filming',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Videography Editing',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Videography Editing',
    alternateName: 'Videography Editing',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Videography Editing',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Videography Editing',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'B2b Video Agency',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'B2b Video Agency',
    alternateName: 'B2b Video Agency',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'B2b Video Agency',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'B2b Video Agency',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Post Production',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Post Production',
    alternateName: 'Post Production',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Post Production',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Post Production',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'End To End Solutions',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'End To End Solutions',
    alternateName: 'End To End Solutions',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'End To End Solutions',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'End To End Solutions',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Book A Crew',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Book A Crew',
    alternateName: 'Book A Crew',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Book A Crew',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Book A Crew',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Creative Videos',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Creative Videos',
    alternateName: 'Creative Videos',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Creative Videos',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Creative Videos',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Production Videos',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Production Videos',
    alternateName: 'Production Videos',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Production Videos',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Production Videos',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Corporate Films',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Corporate Films',
    alternateName: 'Corporate Films',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Corporate Films',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Corporate Films',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Professional Video Services',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Professional Video Services',
    alternateName: 'Professional Video Services',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Professional Video Services',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Professional Video Services',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Advertising Video',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Advertising Video',
    alternateName: 'Advertising Video',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Advertising Video',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Advertising Video',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Digital Media Marketing',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Digital Media Marketing',
    alternateName: 'Digital Media Marketing',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Digital Media Marketing',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Digital Media Marketing',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Brand Campaigns',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Brand Campaigns',
    alternateName: 'Brand Campaigns',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Brand Campaigns',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Brand Campaigns',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Best Commercial Campaigns',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Best Commercial Campaigns',
    alternateName: 'Best Commercial Campaigns',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Best Commercial Campaigns',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Best Commercial Campaigns',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Great Ad Campaigns',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Great Ad Campaigns',
    alternateName: 'Great Ad Campaigns',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Great Ad Campaigns',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Great Ad Campaigns',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Best Campaign Marketing',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Best Campaign Marketing',
    alternateName: 'Best Campaign Marketing',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Best Campaign Marketing',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Best Campaign Marketing',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video Production Agency',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video Production Agency',
    alternateName: 'Video Production Agency',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video Production Agency',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video Production Agency',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video Shoot',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video Shoot',
    alternateName: 'Video Shoot',
    url: 'https://www.redbangle.global/',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video Shoot',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video Shoot',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org/',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Video Production Agency',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Video Production Agency',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 3,
        name: 'Video Shoot',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 4,
        name: 'Best Campaign Marketing',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 5,
        name: 'Great Ad Campaigns',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 6,
        name: 'Brand Campaigns',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 7,
        name: 'Best Commercial Campaigns',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 8,
        name: 'Advertising Video',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 9,
        name: 'Professional Video Services',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 10,
        name: 'Corporate Films',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 11,
        name: 'Production Videos',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 12,
        name: 'Creative Videos',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 13,
        name: 'Book A Crew',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 14,
        name: 'End To End Solutions',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 15,
        name: 'Post Production',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 16,
        name: 'B2b Video Agency',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 17,
        name: 'Videography Editing',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 18,
        name: 'Video Filming',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 19,
        name: 'Drone Photography',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 20,
        name: 'Photographers',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 21,
        name: 'Video And Marketing',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 22,
        name: 'Corporate Videographer',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 23,
        name: 'Explainer Video Production',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 24,
        name: 'Brand Video Agency',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 25,
        name: 'Video Animation Services',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 26,
        name: 'Corporate Video Production Agency',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 27,
        name: 'Video Creation Company',
        item: 'https://www.redbangle.global/',
      },
      {
        '@type': 'ListItem',
        position: 28,
        name: 'Corporate Video',
        item: 'https://www.redbangle.global/',
      },
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'SiteNavigationElement',
    hasPart: [
      { '@context': 'https://schema.org', '@type': 'WebPage', url: '/about' },
      { '@context': 'https://schema.org', '@type': 'WebPage', url: '/crews' },
      { '@context': 'https://schema.org', '@type': 'WebPage', url: '/videos' },
      {
        '@context': 'https://schema.org',
        '@type': 'WebPage',
        url: '/campaigns',
      },
    ],
  },

  {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Corporate Video | Video Creation Company | Corporate Video Production Agency | Video Animation Services | Brand Video Agency | Explainer Video Production | Corporate Videographer | Video And Marketing | Photographers | Drone Photography | Video Filming | Videography Editing | B2b Video Agency | Post Production | End To End Solutions | Book A Crew | Creative Videos | Production Videos | Corporate Films | Professional Video Services Advertising Video | Digital Media Marketing | Brand Campaigns | Best Commercial Campaigns | Great Ad Campaigns | Best Campaign Marketing | Video Production Agency | Video Shoot',
        url: 'https://www.redbangle.global/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Video Professionals | Seamless Support | Who We Are | What Do We Do | What Makes Us Unique | Meet Our Team | Meet Our Professionals | Meet Our Crew | Meet Our Leadership Team | Global Team | International Professionals | Team Culture | Video Creation Company | Professional Video Services',
        url: 'https://www.redbangle.global/about/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Best Commercial Campaigns | Best Campaign Marketing | Famous Advertising Campaigns | Best Recruitment Campaigns | Company Ad Campaigns | Video Ad Campaigns | Active Campaign | Product Ads | Corporate Ads | Best Way To Advertise Your Business | Brand Advertising | Creative Campaigns | Creative Ad | Ad Campaigns | Brand Campaigns | Best Commercial Campaigns | Great Ad Campaigns | Creative Brand Campaigns | Creative Marketing Campaigns',
        url: 'https://www.redbangle.global/campaigns/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Commercial Photographer | Event Photographer | Professional Photographers | Photographers Photography Director | Video Director | Action Camera | Drone With Camera | Photography Crew | Video Crew | Company Headshots | Hire Drone Videographer | Event Photographer | Commercial Photographer | Corporate Professional Headshots | Professional Photo Shoot Video Film Company | Videographer For Rent | Video Shoot | Cinematographer | Videography Real Estate Photography | Product Photography | Aerial Photography | Professional Photographer | Headshot Photography | Drone Photography | Business Headshots | Local Photographers | Best Drone Photography | Corporate Videographer | Hire A Photographer | Jewelry Photography | Best Photographer For Wedding | Camera Crew | Digital Filmmaking | Drone Photo | Commercial Headshot | Contemporary Corporate Headshots',
        url: 'https://www.redbangle.global/crews/',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        id: 'site-navigation',
        name: 'Best Advertising Videos | Leadership Motivation Videos | Video Production Companies Near Me | Marketing Videos | Promotional Videos | Testimonials Videos | Explainer Videos | Product Video | Team Culture Videos | Pre Recorded Video Interview | Corporate Video | Video Production | Video Production Service | Filming Production Companies | Corporate Video Production | Corporate Videography | Event Video Production | Video Animation Services | Animated Video Production | Commercial Production Companies | Explainer Videos | Product Video | Cartoon Animator | Advertising Video | Corporate Video Production | Production Videos | Film Production Agencies | B2b Video Agency | Testimonials Videos | Commercial Video | Inspirational Leadership Video | Promotional Video Companies | Corporate Films | Creative Video Agency | Culture Videos | Marketing Videos | Pr Videos | Ai Generated Videos ',
        url: 'https://www.redbangle.global/videos/',
      },
    ],
  },

  {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Corporate Video | Video Creation Company | Corporate Video Production Agency | Video Animation Services | Brand Video Agency | Explainer Video Production | Corporate Videographer | Video And Marketing | Photographers | Drone Photography | Video Filming | Videography Editing | B2b Video Agency | Post Production | End To End Solutions | Book A Crew | Creative Videos | Production Videos | Corporate Films | Professional Video Services Advertising Video | Digital Media Marketing | Brand Campaigns | Best Commercial Campaigns | Great Ad Campaigns | Best Campaign Marketing | Video Production Agency | Video Shoot',
        url: 'https://www.redbangle.global',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Video Professionals | Seamless Support | Who We Are | What Do We Do | What Makes Us Unique | Meet Our Team | Meet Our Professionals | Meet Our Crew | Meet Our Leadership Team | Global Team | International Professionals | Team Culture | Video Creation Company | Professional Video Services',
        url: 'https://www.redbangle.global/about',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Best Commercial Campaigns | Best Campaign Marketing | Famous Advertising Campaigns | Best Recruitment Campaigns | Company Ad Campaigns | Video Ad Campaigns | Active Campaign | Product Ads | Corporate Ads | Best Way To Advertise Your Business | Brand Advertising | Creative Campaigns | Creative Ad | Ad Campaigns | Brand Campaigns | Best Commercial Campaigns | Great Ad Campaigns | Creative Brand Campaigns | Creative Marketing Campaigns',
        url: 'https://www.redbangle.global/campaigns',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Commercial Photographer | Event Photographer | Professional Photographers | Photographers Photography Director | Video Director | Action Camera | Drone With Camera | Photography Crew | Video Crew | Company Headshots | Hire Drone Videographer | Event Photographer | Commercial Photographer | Corporate Professional Headshots | Professional Photo Shoot Video Film Company | Videographer For Rent | Video Shoot | Cinematographer | Videography Real Estate Photography | Product Photography | Aerial Photography | Professional Photographer | Headshot Photography | Drone Photography | Business Headshots | Local Photographers | Best Drone Photography | Corporate Videographer | Hire A Photographer | Jewelry Photography | Best Photographer For Wedding | Camera Crew | Digital Filmmaking | Drone Photo | Commercial Headshot | Contemporary Corporate Headshots',
        url: 'https://www.redbangle.global/crews',
      },
      {
        '@context': 'https://schema.org',
        '@type': 'SiteNavigationElement',
        '@id': '#table-of-contents',
        name: 'Best Advertising Videos | Leadership Motivation Videos | Video Production Companies Near Me | Marketing Videos | Promotional Videos | Testimonials Videos | Explainer Videos | Product Video | Team Culture Videos | Pre Recorded Video Interview | Corporate Video | Video Production | Video Production Service | Filming Production Companies | Corporate Video Production | Corporate Videography | Event Video Production | Video Animation Services | Animated Video Production | Commercial Production Companies | Explainer Videos | Product Video | Cartoon Animator | Advertising Video | Corporate Video Production | Production Videos | Film Production Agencies | B2b Video Agency | Testimonials Videos | Commercial Video | Inspirational Leadership Video | Promotional Video Companies | Corporate Films | Creative Video Agency | Culture Videos | Marketing Videos | Pr Videos | Ai Generated Videos ',
        url: 'https://www.redbangle.global/videos',
      },
    ],
  },
]
