export const partnersSchema = [
  {
    '@context': 'http://schema.org/',
    '@type': 'CreativeWork',
    text: 'Have a look at our trusted service partners, who help us provide holistic support for your brand content and communication goals.',
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Trusted Collaborators',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/partners',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Trusted Collaborators',
    alternateName: 'Trusted Collaborators',
    url: 'https://www.redbangle.com/partners',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },
  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/partners',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Trusted Collaborators',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Trusted Collaborators',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Content Creation Partners',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/partners',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Content Creation Partners',
    alternateName: 'Content Creation Partners',
    url: 'https://www.redbangle.com/partners',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/partners',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Content Creation Partners',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Content Creation Partners',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Web/App UX design and development',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/partners',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Web/App UX design and development',
    alternateName: 'Web/App UX design and development',
    url: 'https://www.redbangle.com/partners',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },
  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/partners',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Web/App UX design and development',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Web/App UX design and development',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Search engine optimization (SEO)',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/partners',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Search engine optimization (SEO)',
    alternateName: 'Search engine optimization (SEO)',
    url: 'https://www.redbangle.com/partners',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },
  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/partners',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Search engine optimization (SEO)',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Search engine optimization (SEO)',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Written content creation (blog/article)',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/partners',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Written content creation (blog/article)',
    alternateName: 'Written content creation (blog/article)',
    url: 'https://www.redbangle.com/partners',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/partners',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Written content creation (blog/article)',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Written content creation (blog/article)',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Social media management',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/partners',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Social media management',
    alternateName: 'Social media management',
    url: 'https://www.redbangle.com/partners',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/partners',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Social media management',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Social media management',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Digital Performance Marketing',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/partners',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Digital Performance Marketing',
    alternateName: 'Digital Performance Marketing',
    url: 'https://www.redbangle.com/partners',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },
  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/partners',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Digital Performance Marketing',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Digital Performance Marketing',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Public relations',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/partners',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Public relations',
    alternateName: 'Public relations',
    url: 'https://www.redbangle.com/partners',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },
  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/partners',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Public relations',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Public relations',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Live streaming and virtual event production',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/partners',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Live streaming and virtual event production',
    alternateName: 'Live streaming and virtual event production',
    url: 'https://www.redbangle.com/partners',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },
  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/partners',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Live streaming and virtual event production',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Live streaming and virtual event production',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Translations and subtitles',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/partners',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Translations and subtitles',
    alternateName: 'Translations and subtitles',
    url: 'https://www.redbangle.com/partners',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/partners',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Translations and subtitles',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Translations and subtitles',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Augmented reality (AR) and virtual reality (VR)',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/partners',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Augmented reality (AR) and virtual reality (VR)',
    alternateName: 'Augmented reality (AR) and virtual reality (VR)',
    url: 'https://www.redbangle.com/partners',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/partners',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Augmented reality (AR) and virtual reality (VR)',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Augmented reality (AR) and virtual reality (VR)',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Event planning and experiential marketing',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/partners',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Event planning and experiential marketing',
    alternateName: 'Event planning and experiential marketing',
    url: 'https://www.redbangle.com/partners',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/partners',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Event planning and experiential marketing',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Event planning and experiential marketing',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Media planning & buying',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/partners',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Media planning & buying',
    alternateName: 'Media planning & buying',
    url: 'https://www.redbangle.com/partners',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/partners',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Media planning & buying',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Media planning & buying',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Celebrity & Influencer partnerships',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/partners',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Celebrity & Influencer partnerships',
    alternateName: 'Celebrity & Influencer partnerships',
    url: 'https://www.redbangle.com/partners',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/partners',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Celebrity & Influencer partnerships',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Celebrity & Influencer partnerships',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'DTP',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/partners',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'DTP',
    alternateName: 'DTP',
    url: 'https://www.redbangle.com/partners',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },
  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/partners',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'DTP',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'DTP',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Brand Identity Design & Development',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    url: 'https://www.redbangle.com/partners',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress:
        '2nd Floor, Silver Rock, 12, Nandi Durga Road, 1, 1st Main Rd, Bengaluru, Karnataka',
      addressLocality: 'India',
      postalCode: '560046',
      addressCountry: 'IN',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 13.12032,
      longitude: 77.62527,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Brand Identity Design & Development',
    alternateName: 'Brand Identity Design & Development',
    url: 'https://www.redbangle.com/partners',
    logo: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'IN',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.com/partners',
      image: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
    },
    headline: 'Brand Identity Design & Development',
    datePublished: '2011-01-28T17:15:23+08:00',
    dateModified: '2022-01-28T16:12:29+08:00',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Brand Identity Design & Development',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.com/wp-content/uploads/2021/02/logored.png',
      },
    },
  },
]
