export const videoSchema = [
  {
    '@context': 'http://schema.org/',
    '@type': 'CreativeWork',
    text: 'Video creation company producing tailor-made corporate videos, explainer videos, promotional videos & employer branding videos for global enterprises',
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Best Advertising Videos',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Best Advertising Videos',
    alternateName: 'Best Advertising Videos',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Best Advertising Videos',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Best Advertising Videos',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Leadership Motivation Videos',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Leadership Motivation Videos',
    alternateName: 'Leadership Motivation Videos',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Leadership Motivation Videos',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Leadership Motivation Videos',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video Production Companies Near Me',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video Production Companies Near Me',
    alternateName: 'Video Production Companies Near Me',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video Production Companies Near Me',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video Production Companies Near Me',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Marketing Videos',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Marketing Videos',
    alternateName: 'Marketing Videos',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Marketing Videos',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Marketing Videos',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Promotional Videos',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Promotional Videos',
    alternateName: 'Promotional Videos',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Promotional Videos',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Promotional Videos',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Testimonials Videos',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Testimonials Videos',
    alternateName: 'Testimonials Videos',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Testimonials Videos',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Testimonials Videos',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Explainer Videos',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Explainer Videos',
    alternateName: 'Explainer Videos',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Explainer Videos',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Explainer Videos',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Product Video',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Product Video',
    alternateName: 'Product Video',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Product Video',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Product Video',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Team Culture Videos',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Team Culture Videos',
    alternateName: 'Team Culture Videos',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Team Culture Videos',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Team Culture Videos',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Pre Recorded Video Interview',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Pre Recorded Video Interview',
    alternateName: 'Pre Recorded Video Interview',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Pre Recorded Video Interview',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Pre Recorded Video Interview',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Corporate Video',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Corporate Video',
    alternateName: 'Corporate Video',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Corporate Video',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Corporate Video',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video Production',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video Production',
    alternateName: 'Video Production',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video Production',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video Production',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video Production Service',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video Production Service',
    alternateName: 'Video Production Service',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video Production Service',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video Production Service',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Filming Production Companies',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Filming Production Companies',
    alternateName: 'Filming Production Companies',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Filming Production Companies',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Filming Production Companies',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Corporate Video Production',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Corporate Video Production',
    alternateName: 'Corporate Video Production',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Corporate Video Production',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Corporate Video Production',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Corporate Videography',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Corporate Videography',
    alternateName: 'Corporate Videography',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Corporate Videography',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Corporate Videography',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Event Video Production',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Event Video Production',
    alternateName: 'Event Video Production',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Event Video Production',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Event Video Production',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Video Animation Services',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Video Animation Services',
    alternateName: 'Video Animation Services',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Video Animation Services',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Video Animation Services',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Animated Video Production',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Animated Video Production',
    alternateName: 'Animated Video Production',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Animated Video Production',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Animated Video Production',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Commercial Production Companies',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Commercial Production Companies',
    alternateName: 'Commercial Production Companies',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Commercial Production Companies',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Commercial Production Companies',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Explainer Videos',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Explainer Videos',
    alternateName: 'Explainer Videos',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Explainer Videos',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Explainer Videos',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Product Video',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Product Video',
    alternateName: 'Product Video',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Product Video',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Product Video',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Cartoon Animator',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Cartoon Animator',
    alternateName: 'Cartoon Animator',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Cartoon Animator',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Cartoon Animator',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Advertising Video',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Advertising Video',
    alternateName: 'Advertising Video',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Advertising Video',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Advertising Video',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Corporate Video Production',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Corporate Video Production',
    alternateName: 'Corporate Video Production',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Corporate Video Production',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Corporate Video Production',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Production Videos',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Production Videos',
    alternateName: 'Production Videos',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Production Videos',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Production Videos',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Film Production Agencies',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Film Production Agencies',
    alternateName: 'Film Production Agencies',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Film Production Agencies',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Film Production Agencies',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'B2b Video Agency',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'B2b Video Agency',
    alternateName: 'B2b Video Agency',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'B2b Video Agency',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'B2b Video Agency',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Testimonials Videos',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Testimonials Videos',
    alternateName: 'Testimonials Videos',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Testimonials Videos',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Testimonials Videos',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Commercial Video',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Commercial Video',
    alternateName: 'Commercial Video',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Commercial Video',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Commercial Video',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Inspirational Leadership Video',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Inspirational Leadership Video',
    alternateName: 'Inspirational Leadership Video',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Inspirational Leadership Video',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Inspirational Leadership Video',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Promotional Video Companies',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Promotional Video Companies',
    alternateName: 'Promotional Video Companies',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Promotional Video Companies',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Promotional Video Companies',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Corporate Films',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Corporate Films',
    alternateName: 'Corporate Films',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Corporate Films',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Corporate Films',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Creative Video Agency',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Creative Video Agency',
    alternateName: 'Creative Video Agency',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Creative Video Agency',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Creative Video Agency',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Culture Videos',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Culture Videos',
    alternateName: 'Culture Videos',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Culture Videos',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Culture Videos',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Marketing Videos',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Marketing Videos',
    alternateName: 'Marketing Videos',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'Marketing Videos',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'Marketing Videos',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'PR Videos',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'PR Videos',
    alternateName: 'PR Videos',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'PR Videos',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'PR Videos',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'AI Generated Videos',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    url: 'https://www.redbangle.global/videos',
    telephone: '',
    priceRange: '$50',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'United States',
      addressLocality: 'United States',
      postalCode: '',
      addressCountry: 'US',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 37.09024,
      longitude: -95.712891,
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'AI Generated Videos',
    alternateName: 'AI Generated Videos',
    url: 'https://www.redbangle.global/videos',
    logo: 'https://www.redbangle.global/redbangle-logo.png',
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '',
      contactType: 'sales',
      areaServed: 'US',
      availableLanguage: 'en',
    },
    sameAs: [
      'https://www.linkedin.com/company/redbangle/',
      'https://www.facebook.com/redbanglecollab/',
      'https://www.instagram.com/redbanglecollab/',
      'https://www.youtube.com/channel/UCbPlh2ukO1Qz6Ib2fY724QQ',
    ],
  },

  {
    '@context': 'http://schema.org',
    '@type': 'Article',
    image: 'https://www.redbangle.global/redbangle-logo.png',
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': 'https://www.redbangle.global/videos',
      image: 'https://www.redbangle.global/redbangle-logo.png',
    },
    headline: 'AI Generated Videos',
    datePublished: '',
    dateModified: '',
    author: {
      '@type': 'Person',
      name: 'admin',
    },
    description: '',
    publisher: {
      '@type': 'Organization',
      name: 'AI Generated Videos',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.redbangle.global/redbangle-logo.png',
      },
    },
  },

  {
    '@context': 'https://schema.org/',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Best Advertising Videos',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Leadership Motivation Videos',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 3,
        name: 'Video Production Companies Near Me',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 4,
        name: 'Marketing Videos',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 5,
        name: 'Promotional Videos',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 6,
        name: 'Testimonials Videos',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 7,
        name: 'Explainer Videos',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 8,
        name: 'Product Video',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 9,
        name: 'Team Culture Videos',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 10,
        name: 'Pre Recorded Video Interview',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 11,
        name: 'Corporate Video',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 12,
        name: 'Video Production',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 13,
        name: 'Video Production Service',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 14,
        name: 'Filming Production Companies',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 15,
        name: 'Corporate Video Production',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 16,
        name: 'Corporate Videography',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 17,
        name: 'Event Video Production',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 18,
        name: 'Video Animation Services',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 19,
        name: 'Animated Video Production',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 20,
        name: 'Commercial Production Companies',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 21,
        name: 'Explainer Videos',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 22,
        name: 'Product Video',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 23,
        name: 'Cartoon Animator',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 24,
        name: 'Advertising Video',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 25,
        name: 'Corporate Video Production',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 26,
        name: 'Production Videos',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 27,
        name: 'Film Production Agencies',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 28,
        name: 'B2b Video Agency',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 29,
        name: 'Corporate Video',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 30,
        name: 'Testimonials Videos',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 31,
        name: 'Commercial Video',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 32,
        name: 'Inspirational Leadership Video',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 33,
        name: 'Promotional Video Companies',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 34,
        name: 'Corporate Films',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 35,
        name: 'Creative Video Agency',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 36,
        name: 'Culture Videos',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 37,
        name: 'Marketing Videos',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 38,
        name: 'Pr Videos',
        item: 'https://www.redbangle.global/videos',
      },
      {
        '@type': 'ListItem',
        position: 39,
        name: 'Ai Generated Videos',
        item: 'https://www.redbangle.global/videos',
      },
    ],
  },
]
